[project]
name = "sec-nlp-api"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "flask>=2,<3",
    "flask-socketio>=5,<6",
    "psycopg2>=2,<3",
    "python-dotenv>=0,<1",
    "spacy>=3,<4",
]
